### PR TITLE
Fix #588 - Remove ! from WidgetsBinding.instance

### LINKED ISSUE #588: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
Describe the bug

Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

Version (please complete the following information):

Flutter Version: Flutter 3.0.0 • channel stable
OS: Android
flutter_pulltorefresh Version : 2.0.0
Additional context

### PR DESCRIPTION
**Pull request by miquelbeltran**
Fixes https://github.com/peng8350/flutter_pulltorefresh/issues/588 

This issue appeared with Flutter 3.0.0

### CODE REVIEW

**Comment by fzyzcjy** [comment]
+1

**Review by anderson-oki — APPROVED** [review]
Looks good, starting from Flutter 3 `WidgetsBinding.instance` is not nullable anymore.

**Comment by RoyalCoder88** [comment]
hi friends thanks for fixing it, how to get this fixed version? thanks!

**Comment by rudian** [comment]
> hi friends thanks for fixing it, how to get this fixed version? thanks!

the same question here

**Comment by VB10** [comment]
> > hi friends thanks for fixing it, how to get this fixed version? thanks!
> 
> the same question here

right now  you should change pubspec file with this

  pull_to_refresh:
    git: https://github.com/miquelbeltran/flutter_pulltorefresh

**Comment by RoyalCoder88** [comment]
how to? Thanks!

```
dependency_overrides:
  pull_to_refresh:
    git:
    url: https://github.com/miquelbeltran/flutter_pulltorefresh
    path: flutter_pulltorefresh

```
I get this error:
```
153 │ ┌     git:
154 │ │     url: https://github.com/miquelbeltran/flutter_pulltorefresh
155 │ │     path: flutter_pulltorefresh
156 │ │ 
157 │ └ 
    ╵
pub get failed (65;     ╵)
exit code 65
```

**Comment by renshaojuncool** [comment]
> how to? Thanks!
> 
> ```
> dependency_overrides:
>   pull_to_refresh:
>     git:
>     url: https://github.com/miquelbeltran/flutter_pulltorefresh
>     path: flutter_pulltorefresh
> ```
> 
> I get this error:
> 
> ```
> 153 │ ┌     git:
> 154 │ │     url: https://github.com/miquelbeltran/flutter_pulltorefresh
> 155 │ │     path: flutter_pulltorefresh
> 156 │ │ 
> 157 │ └ 
>     ╵
> pub get failed (65;     ╵)
> exit code 65
> ```

try this
```
dependency_overrides:
    pull_to_refresh:
        git:
            url: https://github.com/miquelbeltran/flutter_pulltorefresh
```

**Comment by amadridAgg** [comment]
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^

: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^

: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {

                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance!.addPostFrameCallback((_) {
                       ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^

: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^

: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^

: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').

    WidgetsBinding.instance!.addObserver(this);
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^

: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.

- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

Reloaded 62 of 1134 libraries in 1,104ms.

**Comment by serhatuysal** [comment]
publish please pub.dev

**Review by amadridAgg — APPROVED** [review]

**Review by zeewell — APPROVED** [review]

**Comment by rshrc** [comment]
@peng8350 merging this PR anytime soon?

**Pull request closed without merging**
