### PR TITLE
Update nullsafety version

### PR DESCRIPTION
**Pull request by PcolBP**
Update plugin version because its breaking change.

### CODE REVIEW

**Comment by asterd** [comment]
No news on this merge? without null-safety (and v1.6.4-nullsafety.0 doesn't work) is a big problem. Thanks a lot

**Comment by andoutica** [comment]
`pull_to_refresh: 1.6.1-nullsafety.0 
`
remember that we don't have '^' in version to avoid updating

**Comment by itmediacreations** [comment]
Pre-releases of null-safety versions wont be updated untill you want it.  So untill you will write in pubspec 
`pull_to_refresh: ^2.0.0-nullsafety.1`

**Comment by PcolBP** [comment]
Closing because there is already stable nullsafety version.

**Pull request closed without merging**
